package com.example.model;

import com.logindao.model.IUserModel;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class UserBean  {

	private Long Id;
    /** Not-null value. */
    private static String Username;
    /** Not-null value. */
    private static String Password;
    private  String msg; 
    public UserBean() {
    	
    }

    public UserBean(Long id) {
        this.Id = id;
    }
    public UserBean( String username, String password) {
        
        Username = username;
        Password = password;
    }
    public UserBean(Long id, String username, String password) {
        this.Id = id;
        Username = username;
        Password = password;
    }
  
    public Long getId() {
        return Id;
    }

    public void setId(Long id) {
    	Id = id;
    }

    /** Not-null value. */
    public static String getUsername() {
        return Username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public static void setUsername(String username) {
        Username = username;
    }
    /** Not-null value. */
    public static String getPassword() {
        return Password;
    }
    /** Not-null value; ensure this value is available before it is saved to the database. */
    public static void setPassword(String password) {
        Password = password;
    }
    public  String getmsg() {
        return msg;
    }
    public  void setmsg(String msg) {
        this.msg = msg;
    }
}
